### ISSUE TITLE
Multiple other device(none android) connection

### ISSUE THREAD

**Issue by sinadarvi** [akexorcist/BluetoothSPPLibrary#54]
hi,
i have used your library for my Bluetooth connection between my android phone and one other device,but my project would be complete if i can connect to multiple other device.i try to connect to multiple device with multiple object created from BluetoothSPP class , but when i connect another device my last connection broke and new connection with new device replaced....how can i hold both connection ?

**Comment by terhoraj** [comment]
You cannot with this library as it is now.

**Comment by a458339341** [comment]
淡定
